apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dask.fullname" . }}-jupyter-config
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: jupyter
    namespace: {{ .Values.namespace }}
data:
  password: |
    {{ .Values.password }}