apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-jupyter
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: jupyter
    namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.jupyter.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: jupyter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: jupyter
    spec:
      containers:
        - name: {{ template "dask.fullname" . }}-jupyter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - /root/jupyter-data/start_jupyter.sh
          ports:
            - containerPort: 8888
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /root/jupyter-data
          env:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "dask.fullname" . }}-jupyter-config