logging:
    distributed: info
    distributed.client: warning
    bokeh: critical

# Scheduler options
bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
allowed-failures: 3     # number of retries before a task is considered bad
pdb-on-err: False       # enter debug mode on scheduling error
transition-log-length: 100000

# Worker options
multiprocessing-method: forkserver

# Communication options
compression: auto
tcp-timeout: 300         # seconds delay before calling an unresponsive connection dead
default-scheme: tcp
require-encryption: True   # whether to require encryption on non-local comms
tls:
    ca-file: /Users/erik/code/python/dask2/tls-ca-file.pem
    scheduler:
        cert: /Users/erik/code/python/dask2/tls-cert.pem
        key: /Users/erik/code/python/dask2/tls-key.pem
    worker:
        cert: /Users/erik/code/python/dask2/tls-cert.pem
        key: /Users/erik/code/python/dask2/tls-key.pem
    client:
        cert: /Users/erik/code/python/dask2/tls-cert.pem
        key: /Users/erik/code/python/dask2/tls-key.pem

# Bokeh web dashboard
bokeh-export-tool: False
