kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-doer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "pods", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
