{{ if .Values.jupyter.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spark.fullname" . }}-jupyter-config
  labels:
    app: {{ template "spark.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "spark.chart" . }}
    component: jupyter
    namespace: {{ .Values.namespace }}
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = '{{ .Values.jupyter.password }}'

{{ end }}
