apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "spark.fullname" . }}-worker
  labels:
    app: {{ template "spark.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "spark.chart" . }}
    component: worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "spark.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "spark.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      containers:
        - name: {{ template "spark.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://{{ template "spark.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.worker.resources.limits }}
            - -c
            - {{ .Values.worker.resources.limits.cpu | quote }}
            - -m
            - {{ .Values.worker.resources.limits.memory | quote }}
          {{- end }}
          ports:
            - containerPort: 8789
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
