{{ if .Values.jupyter.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spark.fullname" . }}-jupyter-config
  labels:
    app: {{ template "spark.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "spark.chart" . }}
    component: jupyter
    namespace: {{ .Values.namespace }}
data:
  start_jupyter.sh: |
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -subj '/C=XX/ST=XX/L=XX/O=generated/CN=generated' -keyout /local_cert.pem -out /local_cert.pem
    chmod 444 /local_cert.pem
    echo "
    c = get_config()
    c.NotebookApp.password = '$(python -c "from notebook.auth import passwd; print(passwd('{{ .Values.password }}'), end='')")'
    " > /jupyter_notebook_config.py
    jupyter lab --no-browser --allow-root --ip=0.0.0.0 --certfile=/local_cert.pem --config=/jupyter_notebook_config.py
{{ end }}
