apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "spark.fullname" . }}-scheduler
  labels:
    app: {{ template "spark.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "spark.chart" . }}
    component: scheduler
    namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ template "spark.name" . }}
      release: {{ .Release.Name | quote }}
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "spark.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      containers:
        - name: {{ template "spark.fullname" . }}-scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - bin/spark-class
            - org.apache.spark.deploy.master.Master
          ports:
            - containerPort: {{ .Values.scheduler.uiPort }}
            - containerPort: {{ .Values.scheduler.accessPort }}
