{{ if .Values.jupyter.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}-jupyter
  labels:
    app: {{ template "spark.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "spark.chart" . }}
    component: jupyter
    namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.jupyter.servicePort }}
      targetPort: 8888
  selector:
    app: {{ template "spark.name" . }}
    release: {{ .Release.Name | quote }}
    component: jupyter
  type: {{ .Values.jupyter.serviceType }}

{{ end }}
