apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: scheduler
    namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      containers:
        - name: {{ template "dask.fullname" . }}-scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - dask-scheduler
            - --port
            - "{{ .Values.scheduler.servicePort }}"
            - --bokeh-port
            - "8787"
            - --preload
            - /adaptive_scheduler.py
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
          env:
            - name: NAMESPACE
              value: {{ .Values.namespace }}
            - name: WORKER_MINIMUM
              value: {{ .Values.worker.minimum }}
            - name: WORKER_MAXIMUM
              value: {{ .Values.worker.maximum }}
            - name: WORKER_LABELS
              value: app={{ template "dask.name" . }},component=worker
            - name: WORKER_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: WORKER_IMAGE_PULL_POLICY
              value: {{ .Values.image.pullPolicy }}
            - name: WORKER_RESOURCES
              value: {{ toJson .Values.worker.resources | quote }}
            - name: WORKER_ARGS
              value: dask-worker,{{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }},--nthreads,{{ .Values.worker.resources.limits.cpu | quote }},--memory-limit,{{ .Values.worker.resources.limits.memory | quote }},--no-bokeh,'--host','$(POD_IP)','--name','$(POD_NAME)'
