apiVersion: v1
kind: Service
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: scheduler
    namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: {{ template "dask.fullname" . }}-autoscaler
  automountServiceAccountToken: true
  ports:
    - name: {{ template "dask.fullname" . }}-scheduler
      port: {{ .Values.scheduler.servicePort }}
      targetPort: 8786
    - name: {{ template "dask.fullname" . }}-webui
      port: {{ .Values.webUI.servicePort }}
      targetPort: 8787
  selector:
    app: {{ template "dask.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler
  type: {{ .Values.scheduler.serviceType }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dask.fullname" . }}-autoscaler
  namespace: {{ .Values.namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "dask.fullname" . }}-autoscaler
rules:
- apiGroups: [""]
  resources: ["deployment"]
  resourceNames: ["{{ template "dask.fullname" . }}-worker"]
  verbs: ["update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "dask.fullname" . }}-autoscaler
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "dask.fullname" . }}-autoscaler
subjects:
  - kind: ServiceAccount
    name: {{ template "dask.fullname" . }}-autoscaler
    namespace: {{ .Values.namespace }}