name: spark-chart
version: 1.0.5
appVersion: 0.17.4
description: Distributed computation with Spark on k8s
home: https://spark.pydata.org
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
sources:
- https://github.com/dask/dask
maintainers:
- name: danielfrg
  email: df.rodriguez143@gmail.com
- name: mrocklin
  email: mrocklin@gmail.com
- name: Erik Langenborg
  email: erik.langenborg@gmail.com
