namespace: default

scheduler:
  name: scheduler
  image:
    repository: "spark-trial"
    tag: "v001"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  uiPort: 8080
  accessPort: 7077

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "spark-trial"
    tag: "v001"
    pullPolicy: IfNotPresent
  replicas: 1
  minreplicas: 1
  maxreplicas: 3
  targetCPUUtilizationPercentage: 20
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

jupyter:
  name: jupyter
  enabled: true
  image:
    repository: "spark-trial"
    tag: "v001"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 80
