namespace: default

image:
  repository: "spark-trial"
  tag: "v001"
  pullPolicy: IfNotPresent

scheduler:
  name: scheduler
  replicas: 1
  serviceType: "LoadBalancer"
  uiPort: 8080
  accessPort: 7077
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 2
      memory: 1024Mi


worker:
  name: worker
  replicas: 1
  minreplicas: 1
  maxreplicas: 3
  targetCPUUtilizationPercentage: 20
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

jupyter:
  name: jupyter
  enabled: true
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 80
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
      requests:
        cpu: 1
        memory: 512Mi
