
namespace: default

image:
  repository: "user01e/dask3.6example"
  tag: "v0.3"
  pullPolicy: IfNotPresent


scheduler:
  name: scheduler
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  replicas: 1
  minreplicas: 1
  maxreplicas: 3
  targetCPUUtilizationPercentage: 20
  aptPackages: >-
  env:
    # - name: EXTRA_CONDA_PACKAGES
    #   value: numba xarray -c conda-forge
    # - name: EXTRA_PIP_PACKAGES
    #   value: s3fs dask-ml --upgrade
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

jupyter:
  name: jupyter
  enabled: true
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 443
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  env:
    # - name: EXTRA_CONDA_PACKAGES
    #   value: numba xarray -c conda-forge
    # - name: EXTRA_PIP_PACKAGES
    #   value: s3fs dask-ml --upgrade
  resources: {}
    # limits:
    #   cpu: 2
    #   memory: 6G
    # requests:
    #   cpu: 2
    #   memory: 6G
