
namespace: default

image:
  repository: "user01e/dask"
  tag: "0.1"
  pullPolicy: IfNotPresent


scheduler:
  name: scheduler
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources:
    limits:
      cpu: 1.8
      memory: 6G
    requests:
      cpu: 1
      memory: 1G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  replicas: 0
  aptPackages: >-
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

jupyter:
  name: jupyter
  enabled: true
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 443
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  resources:
    limits:
      cpu: 2
      memory: 3G
    requests:
      cpu: 1
      memory: 1G
