namespace: default

image:
  repository: "user01e/dask"
  tag: "0.7"
  pullPolicy: IfNotPresent

password: dasker

jupyter:
  name: jupyter
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 443
  resources:
    limits:
      cpu: 2
      memory: 2G
    requests:
      cpu: 1
      memory: 512Mi
